### ISSUE TITLE
Can't add friends

### ISSUE THREAD

**Issue by mn200** [SimonS/jankteki#15]
OSX Chrome 50; when I enter names into the text box, neither pressing return, nor pressing the dialog's button does anything (the dialog stays there).  Using the right click menu after selecting a player doesn't do anything either.

**Comment by SimonS** [comment]
thanks for this, I have a feeling this is the bug I'm currently working on, however, to be sure: If you open the chrome developer console (instructions here: https://developer.chrome.com/devtools/docs/console), do you see any red error text in there when you try to add friends?

Again - thanks for the report, if it is the bug is the same, I am literally working on a fix now. If not, that red text should give a better idea of what is happening.

Thanks,

Si

**Comment by SimonS** [comment]
I have just released v0.6.1. Could you take a peek and see if this fixes it? To get the latest version, go to chrome://extensions and click "Update extensions now"/

Thanks!

Si

**Comment by mn200** [comment]
Tried on 0.6.1 and it all seems to work.  Thanks!

**Comment by SimonS** [comment]
:+1:
